version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    restart: always
    networks:
      - rag_network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      qdrant:
        condition: service_started
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - QDRANT_HOST=qdrant  
      - QDRANT_PORT=6333
    restart: always
    networks:
      - rag_network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      backend:
        condition: service_started
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000
    restart: always
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge

